### ISSUE TITLE
ttyS0

### ISSUE THREAD

**Issue by Letztfetz** [forelleblau/ioBroker.gsmsms#13]
Hallo.

Ich bekomme vom Huawei Modem leider nur eine ttxS0 und würde diese gern mit dem Adapter nutzen. Einen /dev/serial/by-id/xxxxxxxxxxx  Ordner hab ich leider nicht. Die Einstellung /dev/ttyS0 funktioniert nicht. 

Wie kann ich die Verbindung zwischen dem Adapter und dem Modem mit ttyS0 umsetzen?

![15](https://github.com/forelleblau/ioBroker.gsmsms/assets/153392201/a59f5693-92d9-4424-b25a-09615e64c567)
![18](https://github.com/forelleblau/ioBroker.gsmsms/assets/153392201/f7bcf1fd-5e76-47aa-ab1b-7b0ffae30df0)
![19](https://github.com/forelleblau/ioBroker.gsmsms/assets/153392201/d6dec60c-0a7c-4edf-b726-b25404d24beb)

**Comment by forelleblau** [comment]
Hallo. Wie lsusb zeig, hast du dein Modem über usb angeschlossen, dann müsstest du es - wenn es für den PI verfügbar ist auch mit dmesg | grep tty sehen. Das angezeigte ttyS0 ist aus meiner Sicht nicht dein Modem.
Was findest du denn im Ordner /dev/serial/by-id  ? Wenn dort dein Modem nicht drin ist, musst du dich ev. ins Thema usb_modeswitch einlesen.

**Comment by Letztfetz** [comment]
Hallo und mal wieder danke für die schnelle Reaktion.

Kurz zur Geschichte. Das Modem wurde beim anstecken lediglich als Datenspeicher angezeigt, dmesg | grep tty brachte kein Ergebnis. Eine Nutzung als Modem so gar nicht möglich. Durch einen Befehl wird nun schon mal das Modem angezeigt. 

/usr/bin/sg_raw /dev/sr0 11 06 20 00 00 00 00 00 01 00

Details dazu hier. https://forums.raspberrypi.com/viewtopic.php?t=18996

Und auch dmesg | grep tty bringt nun das ttyS0. 

Den Ordner /dev/serial/by-id gibt es nicht. Es handelt ich auch inzwischen um einen Docker.

**Comment by Letztfetz** [comment]
Hallo.

Problem gelöst. Unraid unterstützt das ganze einfach nicht. Daher ist ein ioBrocker im Docker auf dieser Plattform in Verbindung mit dem gsmsms Adapter und dem Huawei E3372 nicht umsetzbar. Generell ist das ioBrocker Docker Thema auf unriad sehr anstrengend. Wer zu viel Zeit hat, viel Spaß. Auch die Adapter ham, netatmo, ical machen Probleme, die durch eine Portfreigabe auch nicht behoben sind. Sowohl der Support auch als auch die Community können bei dem speziellen Thema nicht helfen. Die Lösung war ein Umzug in eine VM. Für alle Probleme.

Trotzdem Danke.
