### ISSUE TITLE
Feature: Integrate with Notification Adapter

### ISSUE THREAD

**Issue by Apollon77** [forelleblau/ioBroker.gsmsms#8]
e have a new Notification adapter to centralize notification sending.
I would love that this adapter also supports this.

you "just" need to add a message and flag support in io-package  :-) ... and a bit parsing the data correctly ... 

https://github.com/foxriver76/ioBroker.notification-manager#requirements-for-messaging-adapters

also email and telegram already supprts it ... maybe the "how to parse the dsta into a "string to send" could be taken from there as "blueprint"

**Comment by forelleblau** [comment]
I shoud be able to do the io-package and bit parsing - part. The recipient of the sms (Number) has to be defined in the gsmsms - Adapter (i.e. default-recipient of notifications), right?

**Comment by Apollon77** [comment]
I would say yes... so like a "default receipient for notifications" or such ... @foxriver76 I think we agreed to stay that way for now, right?

**Comment by foxriver76** [comment]
Depends on the adapter, if you have something like a default number in config fine to use it, else I would recommend to simply provide an input field in config for this.

**Comment by forelleblau** [comment]
I just recieved my first notification SMS form notification-manager by gsmsms. With version 0.0.6 available on github.
